### ISSUE TITLE
Launcher is incompatible with versions of PyQt5 before 5.9

### ISSUE THREAD

**Issue by BigRoy** [Colorbleed/launcher#5]
Currently the launcher is incompatible with version prior to Qt 5.9 because of this line:
- https://github.com/Colorbleed/launcher/blob/master/launcher/app.py#L117

This varation of showMessage with QIcon was introduced with Qt 5.9:
- http://doc.qt.io/qt-5/qsystemtrayicon.html#showMessage

Reference of this discussion: 
- https://gitter.im/getavalon/Lobby?at=5a60d317ba39a53f1a304984

**Comment by BigRoy** [comment]
Fixed with #7 thanks to @tokejepsen

**Comment by tokejepsen** [comment]
Now that its compatible with Qt5.8. Could we try to merge this fork to origin?

**Comment by BigRoy** [comment]
Yes, let's! https://github.com/getavalon/launcher/pull/27
